lists/urls.py
from django.conf.urls import url
from lists.views \
import my_lists, share_list, new_list, view_list, NewListView, ViewAndAddToList



urlpatterns = [	
    # url(r'^lists/the-only-list-in-the-world/$', 'lists.views.view_list',
    #     name='view_list'
    # ),
    #url(r'^lists/(.+)/$', 'lists.views.view_list', name='view_list'),
    #url(r'^(\d+)/add_item$', views.add_item, name='add_item'),

    # url(r'^(\d+)/$', view_list, name='view_list'),
    url(r'^(?P<pk>\d+)/$', ViewAndAddToList.as_view(), name='view_list'),
    
    # url(r'^new$', new_list, name='new_list'),
    # url(r'^new$', new_list2, name='new_list'),
    url(r'^new$', NewListView.as_view(), name='new_list'),
    
    url(r'^users/(.+)/$', my_lists, name='my_lists'),
    url(r'^(\d+)/share$', share_list, name='share_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lists.views import HomePageView

urlpatterns = [	
    # url(r'^$', views.home_page, name='home'),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='shared_lists'
    )

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('view_list', args=[self.list.id])

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item, List


EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

# class ItemForm(forms.Form):
class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
        	'text': {'required': EMPTY_LIST_ERROR}
        }

    # item_text = forms.CharField(
    #     widget=forms.fields.TextInput(attrs={
    #         'placeholder': 'Enter a to-do item',
    #         'class': 'form-control input-lg',
    #         }),
    #     )

    # def save(self, for_list):
    #     self.instance.list = for_list
    #     return super().save()


class ExistingListItemForm(ItemForm):
    
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    # def save(self):
    #     return forms.models.ModelForm.save(self)


class NewListForm(ItemForm):
    
    # def save(self, owner):
    #     list_ = List()
    #     if owner:
    #         list_.owner = owner
    #     list_.save()
    #     item = Item()
    #     item.list = list_
    #     item.text = self.cleaned_data['text']
    #     item.save()

    def save(self, owner):
        if owner.is_authenticated():
            return List.create_new(first_item_text=self.cleaned_data['text'], 
                owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

lists/views.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import FormView, CreateView, DetailView
from django.views.generic.detail import SingleObjectMixin

from lists.models import Item, List
from lists.forms import ExistingListItemForm, ItemForm, NewListForm


User = get_user_model()

def home_page(request):
    # if request.method == 'POST':
    #     Item.objects.create(text=request.POST['item_text'])
    #     # return redirect('/')
    #     return redirect('/lists/the-only-list-in-the-world/')

    # items = Item.objects.all()
    # return render(request, 'home.html', {'items': items})
    return render(request, 'home.html', {'form': ItemForm()})


class HomePageView(FormView):
    template_name = 'home.html'
    form_class = ItemForm


# def new_list(request):
#     # list_ = List.objects.create()
#     # item = Item.objects.create(text=request.POST['text'], list=list_)
#     # try:
#     #     item.full_clean()
#     #     item.save()
#     # except ValidationError:
#     #     list_.delete()
#     #     error = "You can't have an empty list item"
#     #     return render(request, 'home.html', {"error" : error})
#     # # return redirect('/lists/the-only-list-in-the-world/')
#     # # return redirect('/lists/%d/' % (list_.id,))
#     # return redirect(list_)

#     form = ItemForm(data=request.POST)
#     if form.is_valid():
#         # Item.objects.create(text=request.POST['text'], list=list_)
#         # list_ = List.objects.create()

#         list_ = List()
#         if request.user.is_authenticated():
#             list_.owner = request.user
#         list_.save()
#         form.save(for_list=list_)
#         return redirect(list_)
#     else:
#         return render(request, 'home.html', {'form': form})


# def new_list2(request):
def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


class NewListView(CreateView):
    template_name = 'home.html'
    form_class = NewListForm

    def form_valid(self, form):
        list_ = form.save(owner=self.request.user)
        return redirect(list_)


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    # error = None
    # items = Item.objects.filter(list=list_)
    # form = ItemForm()
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        # try:
        #     item = Item(text=request.POST['text'], list=list_)
        #     item.full_clean()
        #     item.save()
        #     # return redirect('/lists/%d/' % (list_.id,))
        #     return redirect(list_)
        # except ValidationError:
        #     error = "You can't have an empty list item"
        
        # form = ItemForm(data=request.POST)
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            # Item.objects.create(text=request.POST['text'], list=list_)
            form.save()
            return redirect(list_)
    
    return render(request, 'list.html', {
        'list': list_, 'form': form #, 'error': error
    })


class ViewAndAddToList(CreateView, SingleObjectMixin):
    model = List
    template_name = 'list.html'
    form_class = ExistingListItemForm

    def get_form(self, form_class=form_class):
        self.object = self.get_object()
        if self.request.method == 'POST':
            return form_class(for_list=self.object, data=self.request.POST)
        else:
            return form_class(for_list=self.object)


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

def share_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    list_.shared_with.add(request.POST['email'])
    return redirect(list_)

# def add_item(request, list_id):
#     list_ = List.objects.get(id=list_id)
#     Item.objects.create(text=request.POST['item_text'], list=list_)
#     return redirect('/lists/%d/' % (list_.id,))

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do lists</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>
    <body>
    <div class="container">

        <!-- Spike 'Mozila Persona' -->
        <!--
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <p class="navbar-brand">{{ user }}</p>
                {% if user.email %}
                    <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">Sign out</a>
                {% else %}
                    <a class="btn navbar-btn navbar-right" id="id_login" href="#">Sign in</a>
                {% endif %}
            </div>
        </nav>
        -->
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Superlists</a>
                {% if user.email %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                    </ul>
                    <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">Log out</a>
                    <span class="navbar-text navbar-right">Logged in as {{ user.email }}</span>
                {% else %}
                    <a class="btn navbar-btn navbar-right" id="id_login" href="#">Sign in</a>
                {% endif %}
            </div>
        </nav>

        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>

                    {% block list_form %}
                    <form method="POST" action="{% block from_action %}{% endblock %}">
                    <!-- <input name="item_text" id="id_new_item"
                        class="form-control input-lg"
                        placeholder="Enter a to-do item"
                    /> -->
                    {{ form.text }}    
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="form-group has-error">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                    {% endif %}
                    </form>
                    {% endblock %}
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block extra_content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script src="http://code.jquery.com/jquery.min.js"></script> 
    <script src="https://login.persona.org/include.js"></script>
    <script src="/static/list.js"></script>
    <script src="/static/accounts.js"></script>
    <script>
        /* global $, Superlists, navigator */
        $(document).ready(function() {
            var user = "{{ user.email }}" || null;
            var token = "{{ csrf_token }}";
            var urls = {
                login: "{% url 'persona_login' %}",
                // logout: "{% url 'logout' %}",
            };
            Superlists.Accounts.initialize(navigator, user, token, urls)
        });
    </script>
    <!-- Spike 'Mozila Persona' -->
    <!--
    <script>
        $(document).ready(function() {
            var loginLink = document.getElementById('id_login');
            if(loginLink) {
                loginLink.onclick = function() { navigator.id.request(); };
            }

            var logoutLink = document.getElementById('id_logout');
            if(logoutLink) {
                logoutLink.onclick = function() { navigator.id.logout(); };
            }

            var currentUser = '{{ user.email }}' || null;
            var csrf_token = '{{ csrf_token }}';
            console.log(currentUser);

            navigator.id.watch({
                loggedInUser: currentUser,
                onlogin: function(assertion) {
                    $.post('/accounts/login', { 
                        assertion: assertion, 
                        csrfmiddlewaretoken: csrf_token
                    }).done(function() { window.location.reload(); })
                    .fail(function() { navigator.id.logout(); });
                },
                onlogout: function() {
                    $.post('/accounts/logout', {
                        csrfmiddlewaretoken: csrf_token
                    }).always(function() { window.location.reload(); });
                }
            });
        });
    </script>
    -->
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block from_action %}{% url 'new_list' %}{% endblock %}

<!--
<html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Start a new To-Do list</h1>
        <form method="POST" action="/lists/new">
        // <p style="text-align: center;"> 
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item"/>
        // </p>
        {% csrf_token %}
        </form>
        <table id="id_list_table">
                {% for item in items %}
                    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
                {% endfor %}
        </table>
    </body>
</html>
-->

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block from_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>

    {% if list.owner %}
        <p>List owner: <span id="id_list_owner">{{ list.owner.email }}</span></p>
    {% endif %}
{% endblock %}

{% block extra_content %}
<div class="row">

    <div class="col-md-6">
        <h3>Shared with</h3>
        <ul>
            {% for sharee in list.shared_with.all %}
                <li class="list-sharee">{{ sharee.email }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-4 col-md-offset-1">
        <h3>Share this list:</h3>
        <form class="form-inline" method="POST" action="{% url 'share_list' list.id %}">
            {% csrf_token %}
            <input name="email" placeholder="your-friend@example.com" />
        </form>
    </div>
</div>
{% endblock %}

<!--
<html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="POST" action="/lists/{{ list.id }}/add_item">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item"/>
            {% csrf_token %}
        </form>

        <table id="id_list_table">
            {% for item in list.item_set.all %}
                <tr><td>{{forloop.counter}}: {{ item.text }}</td></tr>
            {% endfor %}
        </table>
    </body>
</html>
-->

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block list_form %}{% endblock %}

{% block header_text %}My Lists{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
    	{% for list in owner.list_set.all %}
    		<li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    	{% endfor %}
    </ul>

    <h2>Lists shared by other user</h2>
    <ul>
    {% for list in owner.shared_lists.all %}
    	<li>
    		<a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
    		({{ list.owner.email }})
    	</li>
    {% endfor %}
    </ul>
{% endblock %}